-- =====================================================================
-- UTrueque · Sprint 3 · HU-03 Publicación de Artículo Académico (issue #4)
-- Migración: catálogo de categorías, tabla public.publicaciones,
-- reglas de negocio, RLS y bucket de Storage "publicaciones".
--
-- Cómo aplicarla: Supabase → SQL Editor → pegar TODO el archivo → Run.
-- Es idempotente: se puede volver a correr sin romper nada.
-- Requiere la migración de HU-02 (tabla public.usuarios con perfil_completo).
--
-- Flujo que sigue la app:
--   1. Sube cada foto a Storage: publicaciones/<id del usuario>/<archivo>.jpg
--   2. Hace UN solo POST /rest/v1/publicaciones con los datos y la lista de
--      rutas de las fotos → la API responde 201 Created.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Catálogo: categorías
--    Vive en una tabla para poder cambiarlo sin tocar la app.
--    Lista inicial; el Product Owner puede editarla desde Supabase.
-- ---------------------------------------------------------------------
create table if not exists public.categorias (
  id      smallint generated by default as identity primary key,
  nombre  text not null unique,
  activo  boolean not null default true,
  orden   smallint not null default 0
);

alter table public.categorias enable row level security;

drop policy if exists "Catalogo categorias legible por autenticados" on public.categorias;
create policy "Catalogo categorias legible por autenticados"
  on public.categorias for select to authenticated using (true);
-- Sin políticas de insert/update/delete: solo se edita desde el panel.

insert into public.categorias (id, nombre, orden) values
  (1, 'Libros y apuntes',                 1),
  (2, 'Calculadoras',                     2),
  (3, 'Batas y uniformes',                3),
  (4, 'Material de laboratorio',          4),
  (5, 'Herramientas de dibujo y diseño',  5),
  (6, 'Electrónica y computación',        6),
  (7, 'Papelería',                        7),
  (8, 'Otros',                            8)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.categorias', 'id'),
              greatest((select max(id) from public.categorias), 1));

-- ---------------------------------------------------------------------
-- 2. Tabla public.publicaciones
--    · modalidad: 'venta' | 'intercambio' | 'gratis'
--    · estado (patrón State): 'disponible' | 'reservado' | 'vendido'
--    · fotos: rutas dentro del bucket "publicaciones" (de 1 a 5),
--      en orden; la primera es la portada. Se guardan rutas y no URLs
--      para no depender del dominio del proyecto.
-- ---------------------------------------------------------------------
create table if not exists public.publicaciones (
  id            uuid primary key default gen_random_uuid(),
  usuario_id    uuid not null default auth.uid()
                references public.usuarios (id) on delete cascade,
  titulo        text not null,
  descripcion   text not null,
  categoria_id  smallint not null references public.categorias (id),
  modalidad     text not null,
  precio        numeric(10, 2),
  estado        text not null default 'disponible',
  fotos         text[] not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- SEGURIDAD: defensa en profundidad. Restricciones iguales a las
-- validaciones de la app (la app no es de confianza).
-- Se agregan solo si no existen, para poder correr el archivo varias veces.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'publicaciones_titulo_chk') then
    alter table public.publicaciones add constraint publicaciones_titulo_chk
      check (char_length(btrim(titulo)) between 3 and 80);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'publicaciones_descripcion_chk') then
    alter table public.publicaciones add constraint publicaciones_descripcion_chk
      check (char_length(btrim(descripcion)) between 10 and 500);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'publicaciones_modalidad_chk') then
    alter table public.publicaciones add constraint publicaciones_modalidad_chk
      check (modalidad in ('venta', 'intercambio', 'gratis'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'publicaciones_estado_chk') then
    alter table public.publicaciones add constraint publicaciones_estado_chk
      check (estado in ('disponible', 'reservado', 'vendido'));
  end if;

  -- Venta: precio obligatorio y mayor a $0.
  -- Intercambio y Gratis: sin precio.
  if not exists (select 1 from pg_constraint where conname = 'publicaciones_precio_chk') then
    alter table public.publicaciones add constraint publicaciones_precio_chk
      check (
        (modalidad = 'venta' and precio is not null and precio > 0)
        or (modalidad <> 'venta' and precio is null)
      );
  end if;

  -- De 1 a 5 fotos, sin huecos (null).
  if not exists (select 1 from pg_constraint where conname = 'publicaciones_fotos_chk') then
    alter table public.publicaciones add constraint publicaciones_fotos_chk
      check (cardinality(fotos) between 1 and 5 and array_position(fotos, null) is null);
  end if;
end $$;

create index if not exists publicaciones_feed_idx      on public.publicaciones (estado, created_at desc);
create index if not exists publicaciones_usuario_idx   on public.publicaciones (usuario_id);
create index if not exists publicaciones_categoria_idx on public.publicaciones (categoria_id);

-- ---------------------------------------------------------------------
-- 3. SEGURIDAD: trigger con reglas que la app no puede saltarse
--    · Toda publicación nace en estado 'disponible'.
--    · Las fotos deben estar en la carpeta del dueño.
--    · No se puede cambiar de dueño ni la fecha de creación.
--    · Cambios de estado permitidos (patrón State):
--        disponible → reservado | vendido
--        reservado  → disponible | vendido
--        vendido    → (ninguno: es el estado final)
-- ---------------------------------------------------------------------
create or replace function public.publicaciones_antes_de_guardar()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.estado     := 'disponible';
    new.created_at := now();
  else
    new.usuario_id := old.usuario_id;
    new.created_at := old.created_at;

    if new.estado is distinct from old.estado and not (
         (old.estado = 'disponible' and new.estado in ('reservado', 'vendido'))
      or (old.estado = 'reservado'  and new.estado in ('disponible', 'vendido'))
    ) then
      raise exception 'Cambio de estado no permitido: % → %', old.estado, new.estado
        using errcode = 'check_violation';
    end if;
  end if;

  if exists (
    select 1 from unnest(new.fotos) as f(ruta)
    where f.ruta not like new.usuario_id::text || '/%'
  ) then
    raise exception 'Las fotos deben estar en la carpeta del dueño de la publicación'
      using errcode = 'check_violation';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists publicaciones_antes_de_guardar on public.publicaciones;
create trigger publicaciones_antes_de_guardar
  before insert or update on public.publicaciones
  for each row execute function public.publicaciones_antes_de_guardar();

-- ---------------------------------------------------------------------
-- 4. SEGURIDAD: RLS (mínimo privilegio y mediación completa)
--    · Leer: cualquier estudiante autenticado.
--    · Crear: solo a su nombre y con el perfil completo (HU-02), porque
--      el filtrado por división y carrera sale del perfil del dueño.
--    · Editar y borrar: solo el dueño.
-- ---------------------------------------------------------------------
alter table public.publicaciones enable row level security;

drop policy if exists "Publicaciones: lectura autenticados" on public.publicaciones;
create policy "Publicaciones: lectura autenticados"
  on public.publicaciones for select to authenticated using (true);

drop policy if exists "Publicaciones: crear la propia" on public.publicaciones;
create policy "Publicaciones: crear la propia"
  on public.publicaciones for insert to authenticated
  with check (
    usuario_id = (select auth.uid())
    and exists (
      select 1 from public.usuarios u
      where u.id = (select auth.uid()) and u.perfil_completo
    )
  );

drop policy if exists "Publicaciones: editar la propia" on public.publicaciones;
create policy "Publicaciones: editar la propia"
  on public.publicaciones for update to authenticated
  using (usuario_id = (select auth.uid()))
  with check (usuario_id = (select auth.uid()));

drop policy if exists "Publicaciones: borrar la propia" on public.publicaciones;
create policy "Publicaciones: borrar la propia"
  on public.publicaciones for delete to authenticated
  using (usuario_id = (select auth.uid()));

-- ---------------------------------------------------------------------
-- 5. SEGURIDAD: Storage, bucket "publicaciones"
--    Público para lectura (las fotos se ven en el Feed), igual que
--    "avatars". La escritura está protegida: cada quien solo sube,
--    cambia o borra en publicaciones/<su id>/.
--    Límite de 5 MB por imagen y solo JPG/PNG, aplicado en el servidor.
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('publicaciones', 'publicaciones', true, 5242880, array['image/jpeg', 'image/png'])
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Publicaciones fotos: lectura autenticados" on storage.objects;
create policy "Publicaciones fotos: lectura autenticados"
  on storage.objects for select to authenticated
  using (bucket_id = 'publicaciones');

drop policy if exists "Publicaciones fotos: subir en carpeta propia" on storage.objects;
create policy "Publicaciones fotos: subir en carpeta propia"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'publicaciones'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Publicaciones fotos: actualizar en carpeta propia" on storage.objects;
create policy "Publicaciones fotos: actualizar en carpeta propia"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'publicaciones'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'publicaciones'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Publicaciones fotos: borrar en carpeta propia" on storage.objects;
create policy "Publicaciones fotos: borrar en carpeta propia"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'publicaciones'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

commit;
