-- =====================================================================
-- UTrueque · Sprint 2 · HU-02 Perfil Académico
-- Migración: catálogo División → Carrera, ajuste de public.usuarios,
-- RLS y bucket de Storage "avatars".
--
-- Cómo aplicarla: Supabase → SQL Editor → pegar TODO el archivo → Run.
-- Es idempotente: se puede volver a correr sin romper nada.
--
-- Parte de este estado (confirmado por el equipo el 29/09/2026):
--   usuarios(id uuid PK → auth.users, nombre_mostrar text, division text,
--            carrera text), RLS activo, políticas:
--     "Usuarios pueden ver su propio perfil"      (select, auth.uid() = id)
--     "Usuarios pueden insertar su propio perfil" (insert, auth.uid() = id)
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Catálogo: divisiones y carreras
--    Viven en tablas para poder cambiar el catálogo sin tocar código.
-- ---------------------------------------------------------------------
create table if not exists public.divisiones (
  id      smallint generated by default as identity primary key,
  nombre  text not null unique,
  activo  boolean not null default true,
  orden   smallint not null default 0
);

create table if not exists public.carreras (
  id          smallint generated by default as identity primary key,
  division_id smallint not null references public.divisiones (id) on delete restrict,
  nombre      text not null,
  activo      boolean not null default true,
  orden       smallint not null default 0,
  constraint carreras_nombre_division_unq unique (division_id, nombre),
  -- Necesario para la FK compuesta de usuarios (carrera ∈ división).
  constraint carreras_id_division_unq unique (id, division_id)
);

create index if not exists carreras_division_idx on public.carreras (division_id);

alter table public.divisiones enable row level security;
alter table public.carreras   enable row level security;

drop policy if exists "Catalogo divisiones legible por autenticados" on public.divisiones;
create policy "Catalogo divisiones legible por autenticados"
  on public.divisiones for select to authenticated using (true);

drop policy if exists "Catalogo carreras legible por autenticados" on public.carreras;
create policy "Catalogo carreras legible por autenticados"
  on public.carreras for select to authenticated using (true);
-- Sin políticas de insert/update/delete: el catálogo solo se edita desde
-- el panel de Supabase (rol service_role), nunca desde la app.

-- ---------------------------------------------------------------------
-- 1.1 SEED PROVISIONAL  ⚠️  NO ES EL CATÁLOGO OFICIAL DE LA UTSJR  ⚠️
--     Sirve solo para poder probar el flujo en el Sprint 2.
--     Cuando tengan la lista oficial: reemplacen estas filas (o
--     desactívenlas con activo = false). La app no necesita cambios.
-- ---------------------------------------------------------------------
insert into public.divisiones (id, nombre, orden) values
  (1, 'División de Tecnologías de la Información (PROVISIONAL)', 1),
  (2, 'División Industrial (PROVISIONAL)',                       2),
  (3, 'División Económico-Administrativa (PROVISIONAL)',         3)
on conflict (id) do nothing;

insert into public.carreras (id, division_id, nombre, orden) values
  (1, 1, 'Ingeniería en Desarrollo y Gestión de Software (PROVISIONAL)', 1),
  (2, 1, 'Ingeniería en Redes Inteligentes y Ciberseguridad (PROVISIONAL)', 2),
  (3, 2, 'Ingeniería en Mantenimiento Industrial (PROVISIONAL)',         1),
  (4, 2, 'Ingeniería en Mecatrónica (PROVISIONAL)',                      2),
  (5, 3, 'Licenciatura en Administración (PROVISIONAL)',                 1),
  (6, 3, 'Licenciatura en Contaduría (PROVISIONAL)',                     2)
on conflict (id) do nothing;

-- Mueve los contadores de identity para que futuros inserts no choquen.
select setval(pg_get_serial_sequence('public.divisiones', 'id'),
              greatest((select max(id) from public.divisiones), 1));
select setval(pg_get_serial_sequence('public.carreras', 'id'),
              greatest((select max(id) from public.carreras), 1));

-- ---------------------------------------------------------------------
-- 2. Ajuste de public.usuarios
-- ---------------------------------------------------------------------
alter table public.usuarios
  add column if not exists division_id     smallint references public.divisiones (id),
  add column if not exists carrera_id      smallint,
  add column if not exists foto_url        text,
  add column if not exists perfil_completo boolean not null default false,
  add column if not exists created_at      timestamptz not null default now(),
  add column if not exists updated_at      timestamptz not null default now();

-- La carrera debe pertenecer a la división elegida (FK compuesta).
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'usuarios_carrera_division_fkey') then
    alter table public.usuarios
      add constraint usuarios_carrera_division_fkey
      foreign key (carrera_id, division_id)
      references public.carreras (id, division_id);
  end if;

  -- Nombre de 3 a 50 caracteres (igual que la validación de la app).
  -- NOT VALID: no revisa filas viejas, pero sí todo insert/update nuevo.
  if not exists (select 1 from pg_constraint where conname = 'usuarios_nombre_longitud_chk') then
    alter table public.usuarios
      add constraint usuarios_nombre_longitud_chk
      check (nombre_mostrar is null or char_length(btrim(nombre_mostrar)) between 3 and 50)
      not valid;
  end if;
end $$;

-- Las columnas de texto antiguas se conservan para no romper HU-01,
-- pero ya no se usan. Se pueden borrar en un sprint posterior.
comment on column public.usuarios.division is 'OBSOLETA desde HU-02: usar division_id';
comment on column public.usuarios.carrera  is 'OBSOLETA desde HU-02: usar carrera_id';

-- Trigger: la base calcula perfil_completo y updated_at (la app no
-- puede "marcarse" como completa sin tener los datos).
create or replace function public.usuarios_antes_de_guardar()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.perfil_completo :=
        new.nombre_mostrar is not null
    and char_length(btrim(new.nombre_mostrar)) between 3 and 50
    and new.division_id is not null
    and new.carrera_id  is not null;
  new.updated_at := now();
  if tg_op = 'UPDATE' then
    new.created_at := old.created_at;
  end if;
  return new;
end;
$$;

drop trigger if exists usuarios_antes_de_guardar on public.usuarios;
create trigger usuarios_antes_de_guardar
  before insert or update on public.usuarios
  for each row execute function public.usuarios_antes_de_guardar();

-- Las filas que ya existían quedan con perfil_completo = false (valor por
-- defecto), porque todavía no tienen division_id ni carrera_id: esos
-- usuarios verán "Completar perfil" en su próximo inicio de sesión.

-- Trigger: crea la fila de perfil vacía cuando alguien se registra.
create or replace function public.crear_perfil_al_registrarse()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.usuarios (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists crear_perfil_al_registrarse on auth.users;
create trigger crear_perfil_al_registrarse
  after insert on auth.users
  for each row execute function public.crear_perfil_al_registrarse();

-- Crea la fila para usuarios que se registraron antes de este trigger.
insert into public.usuarios (id)
select u.id from auth.users u
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- 3. RLS de public.usuarios
-- ---------------------------------------------------------------------
alter table public.usuarios enable row level security;

-- Antes: cada quien solo veía su propio perfil. Ahora cualquier usuario
-- autenticado puede leer los perfiles (nombre, división, carrera, foto),
-- porque se necesitan en publicaciones y chat. La tabla NO guarda el
-- correo ni datos privados (esos viven en auth.users).
drop policy if exists "Usuarios pueden ver su propio perfil" on public.usuarios;
drop policy if exists "Autenticados pueden ver perfiles publicos" on public.usuarios;
create policy "Autenticados pueden ver perfiles publicos"
  on public.usuarios for select to authenticated using (true);

-- Se mantiene la política de insert existente (solo su propia fila).
drop policy if exists "Usuarios pueden insertar su propio perfil" on public.usuarios;
create policy "Usuarios pueden insertar su propio perfil"
  on public.usuarios for insert to authenticated
  with check (auth.uid() = id);

drop policy if exists "Usuarios pueden actualizar su propio perfil" on public.usuarios;
create policy "Usuarios pueden actualizar su propio perfil"
  on public.usuarios for update to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);
-- Sin política de delete: el perfil se borra solo en cascada con auth.users.

-- ---------------------------------------------------------------------
-- 4. Storage: bucket "avatars"
--    Recomendación: bucket PÚBLICO (lectura por URL pública).
--    · Las fotos se muestran en feed y chat a todos los estudiantes.
--    · Las URLs firmadas caducan, hay que regenerarlas y no se cachean bien.
--    · La escritura sigue protegida: cada quien solo sube a avatars/<su id>/.
--    Límite de 5 MB y solo JPG/PNG aplicado también aquí, en el servidor.
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 5242880, array['image/jpeg', 'image/png'])
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Avatars: lectura autenticados" on storage.objects;
create policy "Avatars: lectura autenticados"
  on storage.objects for select to authenticated
  using (bucket_id = 'avatars');

drop policy if exists "Avatars: subir en carpeta propia" on storage.objects;
create policy "Avatars: subir en carpeta propia"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Avatars: actualizar en carpeta propia" on storage.objects;
create policy "Avatars: actualizar en carpeta propia"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Avatars: borrar en carpeta propia" on storage.objects;
create policy "Avatars: borrar en carpeta propia"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

commit;
